- id: knop1
  alias: Schakelaar 1 links > Eating
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0001639d5a
      click_type: single
  action:
    - service: homeassistant.turn_on
      entity_id: scene.Eating

- id: knop2
  alias: Schakelaar 1 rechts > Evening
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0001639d5a
      click_type: single
  action:
    - service: homeassistant.turn_on
      entity_id: scene.evening

- id: knop3
  alias: Schakelaar 2 links > Maximum
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_left_158d0001710729
      click_type: single
  action:
  - service: light.toggle
    data:
      entity_id: light.keukenlamp

- id: knop4
  alias: Schakelaar 2 rechts > Off
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.wall_switch_right_158d0001710729
      click_type: single
  action:
  - service: light.turn_off
    data:
      entity_id: group.all_lights
      
- id: LightsOnAutoWhenMotion
  alias: Lights on when motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000222df56
      to: 'on'
  condition: 
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.lampentafel
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: scene.Eating

- id: GetSonoffStateOnHAStartUp
  alias: "Get Sonoff state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoffs/power1"
        payload: ""

- id: HassioBootNotification
  alias: "Notification when Hassio boots"
  trigger:
    platform: homeassistant
    event: start
  action:
   - service: notify.simplepush
     data:
        title: "Hassio boots"
        message: "Hassio boots"

- id: 'WasmachineKlaar'
  alias: Wasmachine - klaar
  condition: []
  trigger:
  - below: '10'
    entity_id: sensor.wasmachine
    platform: numeric_state
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.washingmachine_bezig
      

- id: 'WasmachineBezig'
  alias: Wasmachine - bezig
  condition: []
  trigger:
  - above: '10'
    entity_id: sensor.wasmachine
    platform: numeric_state
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.washingmachine_bezig

- id: 'WasmachineNotificatie'
  alias: Wasmachine - notificatie
  condition: []
  trigger:
  - platform: state
    entity_id: input_boolean.washingmachine_bezig
    from: 'on' 
    to: 'off'
    for:
      minutes: 5
  action: 
   - service: notify.simplepush
     data:
        title: "Wasmachine klaar"
        message: "Wasmachine klaar"
   - service: notify.ios_marleen_marleen01
     data:
        title: "Wasmachine klaar"
        message: "Wasmachine klaar"

- id: 'TuinlichtAanBijZonsondergang'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.licht_in_tuin

- id: 'TuinlichtUitNaEenTijdje'
  trigger:
    platform: sun
    event: sunset
    offset: "+02:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.licht_in_tuin

- id: 'TuinNotificatie'
  alias: Poort of schuur open / niemand thuis
  condition: 
    condition: and
    conditions:
    - condition: template
      value_template: "{{ states('device_tracker.marleen_marleen01') != 'home' }}"
    - condition: template
      value_template: "{{ states('device_tracker.Kees_kees01') != 'home' }}"
  trigger:
  - platform: state
    entity_id: sensor.poortdeur
    to: 'open'
    for:
      minutes: 2
  - platform: state
    entity_id: sensor.schuurdeur
    to: 'open'
    for:
      minutes: 2
  action: 
   - service: notify.simplepush
     data:
        title: "Schuur/poort open"
        message: "En er is niemand thuis!"
   - service: notify.ios_marleen_marleen01
     data:
        title: "Schuur/poort open"
        message: "En er is niemand thuis!"

- id: 'RebootDafangEveryNight'
  alias: Reboot Dafang every night 
  trigger:
  - platform: time
    at: '01:00:00'
  action: 
    service: rest_command.reboot_dafang

- id: 'EventGridTest'
  alias: EventGridTest
  trigger:
  - platform: time
    minutes: '/3'
    seconds: 00
  action: 
    service: notify.eventgrid
    message: "Your message goes here"
    title: "Custom subject"
    data: "{ }"