- platform: mqtt
  name: Schuurdeur
  state_topic: "motion/door"
  payload_on: "open"
  payload_off: "closed"

- platform: mqtt
  name: Poortdeur
  state_topic: "motion/gate"
  payload_on: "open"
  payload_off: "closed"

- platform: mqtt
  name: FietsJasmijn
  state_topic: "motion/bike/jasmijn"
  payload_on: "visible"
  payload_off: "not visible"

- platform: mqtt
  name: FietsMarleen
  state_topic: "motion/bike/marleen"
  payload_on: "visible"
  payload_off: "not visible"

- platform: workday
  country: NL 