- platform: mqtt
  name: Schuurdeur
  state_topic: "motion/door"
  payload_on: "open"
  payload_off: "closed"
- platform: mqtt
  name: Poortdeur
  state_topic: "motion/gate"
  payload_on: "open"
  payload_off: "closed"
- platform: mqtt
  name: FietsJasmijn
  state_topic: "motion/bike/jasmijn"
  payload_on: "visible"
  payload_off: "not visible"
- platform: mqtt
  name: FietsMarleen
  state_topic: "motion/bike/marleen"
  payload_on: "visible"
  payload_off: "not visible"
- platform: trend
  sensors:
    kees1:
      entity_id: sensor.kees_naar_huis
      device_class: moving
      min_gradient: -0.0138 #if remaining travel time drops 50min per hour (-50)/(60*60)
    kees2:
      entity_id: sensor.kees_naar_huis
      device_class: moving
      min_gradient: -0.00138 
    kees3:
      entity_id: sensor.kees_naar_huis
      device_class: moving
      min_gradient: 0.00138 
    kees4:
      entity_id: sensor.kees_naar_huis
      device_class: moving
      min_gradient: 0.0138 
    kees5:
      entity_id: sensor.kees_naar_huis
      device_class: moving
      min_gradient: -0.138