- platform: xiaomi_miio #ok
  name: staandelamp
  host: philips-light-bulb_miio61632965.localdomain
  token: !secret staandelamp_token
- platform: xiaomi_miio #ok
  name: bank
  host: philips-light-bulb_miio61510856.localdomain
  token: !secret bank_token
- platform: xiaomi_miio
  name: tafel1
  host: philips-light-bulb_miio61623717.localdomain
  token: !secret tafel1_token
- platform: xiaomi_miio #ok
  name: tafel2
  host: philips-light-bulb_miio61511979.localdomain
  token: !secret tafel2_token
- platform: xiaomi_miio
  name: tafel3
  host: philips-light-bulb_miio60379202.localdomain
  token: !secret tafel3_token
- platform: group
  name: LampenTafel
  entities:
    - light.tafel1
    - light.tafel2
    - light.tafel3 
- platform: group
  name: Hall Light
  entities:
    - light.0x90fd9ffffe10c5d1_light
    - light.0x90fd9ffffe135ab2_light
- platform: mqtt
  name: kitchen
  state_topic: "stat/kitchen/POWER"
  command_topic: "cmnd/kitchen/POWER"
  availability_topic: "tele/kitchen/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: mqtt
  name: Attic
  state_topic: "stat/attic/POWER"
  command_topic: "cmnd/attic/POWER"
  availability_topic: "tele/attic/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
- platform: group
  name: Livingroom
  entities:
    - light.staandelamp
    - light.bank
    - light.LampenTafel
    - light.kitchen_light

