 
- platform: systemmonitor
  scan_interval: 300
  resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use

- platform: template
  sensors:   
    strom_tarif:
      friendly_name: "Electricity tarif"
      unit_of_measurement: EUR
      value_template:  "
          {% if now().weekday() >= 0 
              and now().weekday() < 5 
              and now().hour >= 7
              and now().hour < 20 %}  0.20834
          {% elif now().weekday() == 5 
              and now().hour >= 7 
              and now().hour < 13 %} 0.20834
          {% else %} 0.1827
          {% endif %}"
