- platform: google_travel_time
  name: Kees naar huis
  api_key: !secret google_api_key
  origin: device_tracker.iphone_van_kees
  destination: zone.home
  options:
    mode: driving

- platform: systemmonitor
  scan_interval: 300
  resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use

- platform: buienradar
  name: rotterdam
  monitored_conditions:
    - temperature