- platform: yr

- platform: google_travel_time
  name: Kees naar huis
  api_key: !secret google_api_key
  origin: device_tracker.kees_kees01
  destination: zone.home
  options:
    mode: driving

- platform: template
  sensors:
    kees_travel_km_back_home: 
      unit_of_measurement: 'km'
      value_template: "{{ states.sensor.kees_naar_huis.distance.elevation | float }}"
    kees_distance_km_back_home: 
      unit_of_measurement: 'km'
      value_template: "{{ states.proximity.home | float }}"

- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

- platform: mqtt
  state_topic: "zigbee2mqtt/0x00158d000222df56"
  name: 0x00158d000222df56_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.battery }}'
  device_class: battery

- platform: mqtt
  state_topic: "zigbee2mqtt/0x00158d0001f5358e"
  name: 0x00158d0001f5358e_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.battery }}'
  device_class: battery

- platform: mqtt
  state_topic: "zigbee2mqtt/0x00158d0001639d5a"
  name: 0x00158d0001639d5a_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.battery }}'
  device_class: battery

- platform: mqtt
  state_topic: "zigbee2mqtt/0x00158d0001710729"
  name: 0x00158d0001710729_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.battery }}'
  device_class: battery

- platform: mqtt
  state_topic: "zigbee2mqtt/0x00158d0001f9faa1"
  name: 0x00158d0001f9faa1_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.battery }}'
  device_class: battery

- platform: mqtt
  state_topic: "zigbee2mqtt/0x00158d000208e0e0"
  name: 0x00158d000208e0e0_battery
  unit_of_measurement: "%"
  value_template: '{{ value_json.battery }}'
  device_class: battery

- platform: alpha_vantage
  api_key: !secret alpha_vantage_key
  symbols:
  - symbol: MSFT
    name: Microsoft

- platform: ups
  username: !secret ups_username
  password: !secret ups_password

- platform: postnl
  name: PostNl
  username: !secret postnl_username
  password: !secret postnl_password

- platform: buienradar
  name: 'Rotterdam' 
  monitored_conditions:
    - condition
    - temperature
    - condition_1d
    - temperature_1d