- platform: yr

- platform: google_travel_time
  name: Kees naar huis
  api_key: !secret google_api_key
  origin: device_tracker.kees_kees01
  destination: zone.home
  options:
    mode: driving

- platform: template
  sensors:
    kees_travel_km_back_home: 
      unit_of_measurement: 'km'
      value_template: "{{ states.sensor.kees_naar_huis.distance | float }}"
    kees_distance_km_back_home: 
      unit_of_measurement: 'km'
      value_template: "{{ states.proximity.home | float }}"
    toon_target_temperature:
      value_template: '{{ states.climate.toon_thermostat.attributes.temperature }}'
      friendly_name: 'Target Temperatuur'
      unit_of_measurement: '°C'
    toon_current_temperature:
      value_template: '{{ states.climate.toon_thermostat.attributes.current_temperature }}'
      friendly_name: 'Current Temperatuur'
      unit_of_measurement: '°C'

- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: processor_use

- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

- platform: ups
  username: !secret ups_username
  password: !secret ups_password

- platform: postnl
  name: PostNl
  username: !secret postnl_username
  password: !secret postnl_password

- platform: buienradar
  name: 'Rotterdam' 
  monitored_conditions:
    - condition
    - temperature
    - condition_1d
    - temperature_1d

- platform: seventeentrack
  username: !secret 17track_username
  password: !secret 17track_password