title: Home
resources:
  - url: /local/community/banner-card/banner-card.js?v=1
    type: module
  - url: /local/community/simple-thermostat/simple-thermostat.js?v=1
    type: module
views:   
  - !include lovelace/home.yaml
  - !include lovelace/1st_floor.yaml
  - !include lovelace/attic.yaml