title: Home
views:
  - id: home
    title: Home
    badges:
      - device_tracker.marleen_marleen01
      - device_tracker.kees_kees01
      - sensor.postnl
      - sensor.ups
    cards:
      - id: tracker_history
        type: history-graph
        entities:
        - device_tracker.marleen_marleen01
        - device_tracker.kees_kees01
      - id: map
        type: picture-entity
        title: Kees & Marleen
        entity: camera.locations
        camera_image: camera.locations
        show_state: false
        show_name: true
        tap_action: dialog
      - id: living_room
        type: glance
        title: Living room  
        columns: 3
        entities:
          - entity: binary_sensor.0x00158d000222df56_occupancy
            name: Occupancy
          - entity: light.kitchen
            name: Kitchen
            tap_action: toggle
          - entity: sensor.toon_current_temperature
            name: "Temperature"
          - entity: scene.eating
            name: Eating
            icon: mdi:food
            tap_action:
             action: call-service
             service: scene.turn_on
             service_data: 
               entity_id: scene.eating
          - entity: scene.evening
            name: Evening
            icon: mdi:weather-sunset
            tap_action:
             action: call-service
             service: scene.turn_on
             service_data: 
               entity_id: scene.evening
          - entity: scene.living_room_lights_off
            name: All off
            icon: mdi:weather-night
            tap_action:
             action: call-service
             service: scene.turn_on
             service_data: 
               entity_id: scene.living_room_lights_off
      - id: backyard
        type: picture-glance
        title: Backyard
        entities:
          - switch.licht_in_tuin
          - binary_sensor.schuurdeur
          - binary_sensor.poortdeur
          - binary_sensor.fietsjasmijn
          - binary_sensor.fietsmarleen
          - entity: camera.dafang
            name: Live
        camera_image: camera.dafang_motion_snapshot
        tap_action: dialog
      - id: front_door
        type: picture-entity
        name: Front door
        entity: camera.front_door_latest
        camera_image: camera.front_door_latest
        show_info: false
      - id: hallway
        type: entities
        title: Hallway
        entities: 
          - timer.hallway_lights_off_in 
          - light.hall_light
          - switch.doorbell_buzzer_enabled
          - binary_sensor.0x00158d0001f9faa1_occupancy
      - id: kees_naar_huis
        type: history-graph
        entities: [sensor.kees_naar_huis]
        hours_to_show: 12
        icon: mdi:car
        title: "Kees naar huis"
      - id: temperatures
        type: history-graph
        entities: 
          - entity: sensor.0x00158d0001f5358e_temperature
            name: "Bathroom"
          - entity: sensor.rotterdam_temperature
            name: "Outside"
          - entity: sensor.toon_current_temperature
            name: "Toon Current"
          - entity: sensor.toon_target_temperature
            name: "Toon Target"
        hours_to_show: 12
        title: "Temperatures"
      - id: living_room_all
        type: entities
        title: Individual lights
        show_header_toggle: false
        entities:
          - light.staandelamp
          - light.bank
          - light.lampentafel
          - light.kitchen
          - light.hall_light
  - id: 1st_floor_tab
    title: 1st floor & attic
    cards:
      - id: hallway_1st_floor
        type: entities
        title: Hallway
        entities: 
          - light.lights_hallway_1st_floor
          - timer.hallway_1st_floor_lights_off_in 
          - binary_sensor.0x00158d0002e2ab4d_occupancy 
      - id: motion_first_floor_card
        type: history-graph
        hours_to_show: 24
        title: "Motion"
        entities:
        - binary_sensor.0x00158d0002e2ab4d_occupancy
      - id: showering_card
        type: history-graph
        hours_to_show: 24
        title: "Showering"
        entities:
        - binary_sensor.showering
      - id: temperature_bathroom_card
        type: history-graph
        hours_to_show: 24
        title: "Bathroom temperature"
        entities: 
          - entity: sensor.0x00158d0001f5358e_temperature
            name: "Bathroom"
      - id: humidity_card
        type: history-graph
        hours_to_show: 24
        title: "Bathroom humidity"
        entities: 
          - entity: sensor.0x00158d0001f5358e_humidity
      - id: attic_card
        type: entities
        title: Attic
        entities: 
          - light.attic  
  - id: system
    title: Systeem
    icon: mdi:settings
    cards:
      - id: dafang
        type: entities
        title: Dafang
        show_header_toggle: true
        entities:
          - switch.dafang_h264_rtsp_server
          - switch.dafang_mjpeg_rtsp_server
          - sensor.dafang_light_sensor
          - switch.dafang_ir_filter
          - switch.dafang_ir_led
          - switch.dafang_night_mode
          - switch.dafang_night_mode_auto
          - switch.dafang_blue_led
          - switch.dafang_yellow_led
          - switch.dafang_motion_detection
          - switch.dafang_motion_tracking
          - binary_sensor.dafang_motion_sensor
      - id: backyard_live
        type: picture-entity
        title: Backyard live
        entity: camera.dafang
        camera_image: camera.dafang
        show_info: true
        tap_action: dialog
      - id: backyard_latest_snapshop
        type: picture-entity
        title: Backyard latest motion snapshot
        entity: camera.dafang_motion_snapshot
        camera_image: camera.dafang_motion_snapshot
        show_info: true
        tap_action: dialog        
      - id: front_door_live
        type: picture-entity
        title: Front door Live 
        entity: camera.front_door
        camera_image: camera.front_door
        show_info: true
        tap_action: dialog   
      - id: zigbee
        type: entities
        title: Zigbee
        show_header_toggle: true
        entities:
          - input_boolean.zigbee_permit_join
          - timer.zigbee_permit_join
          - sensor.bridge_state
      - id: batteries
        type: entities
        title: batteries
        show_header_toggle: true
        entities:
          - sensor.0x00158d0001f5358e_battery
          - sensor.0x00158d000222df56_battery
          - sensor.0x00158d0001639d5a_battery
          - sensor.0x00158d0001f9faa1_battery
          - sensor.0x00158d000208e0e0_battery
          - sensor.0x00158d0001710729_battery