title: Home
resources:
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /customcards/github/nervetattoo/banner-card.js?track=true
    type: module
views:   
  - !include lovelace/home.yaml
  - !include lovelace/1st_floor.yaml
  - !include lovelace/attic.yaml