title: Home
views:   
  - !include lovelace/home.yaml
  - !include lovelace/1st_floor.yaml
  - !include lovelace/system.yaml
  - id: zigbeemap
    title: Zigbee
    panel: true
    icon: mdi:graphql
    cards:
      - type: iframe 
        url: /local/zigbee2mqtt_networkmap/map.html
        aspect_ratio: 75%            
