esphome:
  name: attic
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  networks:
  - ssid: !secret attic_wifi_ssid
    password:  !secret doorbell_wifi_password
  - ssid: !secret doorbell_wifi_ssid
    password:  !secret doorbell_wifi_password 

api:
  password: !secret doorbell_ota_password

logger:

ota:
  password: !secret doorbell_ota_password

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "attic_switch" 
    on_press:
      then:
        - light.toggle: attic_light
    on_release:
      then:
        - light.toggle: attic_light

light:
  - platform: binary
    id: attic_light
    name: "attic_light"
    output: attic_relay

output:
  - platform: gpio
    id: attic_relay
    pin: GPIO4
 
switch:
  - platform: restart
    name: "Attic floor Restart"