esphomeyaml:
  name: bathroom_main
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret doorbell_wifi_ssid
  password: !secret doorbell_wifi_password

mqtt:
  broker: !secret doorbell_mqtt_broker
  username: !secret doorbell_mqtt_user
  password: !secret doorbell_mqtt_password

logger:

ota:
  password: !secret doorbell_ota_password

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "bathroom_main_switch" 
    on_press:
      then:
        - light.toggle: bathroom_main_light
    on_release:
      then:
        - light.toggle: bathroom_main_light

light:
  - platform: binary
    id: bathroom_main_light
    name: "Lights hallway 1st floor"
    output: bathroom_main_relay

output:
  - platform: gpio
    id: bathroom_main_relay
    pin: GPIO4
 