esphome:
  name: doorbell
  platform: ESP8266
  board: nodemcuv2

wifi:
  networks:
  - ssid: !secret esphome_wifi_1_ssid
    password: !secret esphome_wifi_1_password
  - ssid: !secret esphome_wifi_2_ssid
    password: !secret esphome_wifi_2_password 
  # manual_ip:
  #   static_ip: 192.168.2.105
  #   gateway: !secret esphome_network_gateway 
  #   subnet: !secret esphome_network_subnet 
  #   dns1: !secret esphome_network_dns1 
  # use_address: 192.168.2.17
  ap:
    ssid: "Esphome Doorbell"
    password: !secret esphome_ap_password 

captive_portal: 

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_webserver_password

api:
  password: !secret esphome_api_password

logger:

ota:
  password: !secret esphome_ota_password

switch:
  - id: "doorbell_buzzer"
    name: "doorbell_buzzer"
    platform: gpio
    inverted: yes
    pin:
      number: D4

  - id: "doorbell_buzzer_enabled"
    name: "Doorbell Buzzer Enabled"
    platform: gpio
    pin:
      number: D2 # Nothing connected to this pin, just acts as an input_boolean / state variable
    
binary_sensor:
  - platform: gpio
    id: doorbell_button
    name: "Doorbell Button"
    pin: D5
    on_press:
      if:
        condition:
          lambda: 'return id(doorbell_buzzer_enabled).state;'
        then:
          - switch.turn_on:
              id: doorbell_buzzer
          - delay: 750ms
          - switch.turn_off:
              id: doorbell_buzzer
