esphomeyaml:
  name: doorbell
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret doorbell_wifi_ssid
  password: !secret doorbell_wifi_password

mqtt:
  broker: !secret doorbell_mqtt_broker
  username: !secret doorbell_mqtt_user
  password: !secret doorbell_mqtt_password

logger:

ota:
  password: !secret doorbell_ota_password

switch:
  - id: "doorbell_buzzer"
    name: "doorbell_buzzer"
    platform: gpio
    pin:
      number: D4
      inverted: True

  - id: "doorbell_buzzer_enabled"
    name: "Doorbell Buzzer Enabled"
    platform: gpio
    pin:
      number: D2 # Nothing connected to this pin, just acts as an input_boolean / state variable
    
binary_sensor:
  - platform: gpio
    id: doorbell_button
    name: "Doorbell Button"
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    filters:
      - delayed_off: 750ms # someone cannot push the button twice
      #- delayed_on: 200ms # you have to push it for 0,2 sec
    on_press:
      if:
        lambda: 'return id(doorbell_buzzer_enabled).value;'
      then:
        - switch.turn_on:
            id: doorbell_buzzer
        - delay: 750ms
        - switch.turn_off:
            id: doorbell_buzzer
