esphome:
  name: frontdoorcamera
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  networks:
  - ssid: !secret esphome_wifi_1_ssid
    password: !secret esphome_wifi_1_password
  - ssid: !secret esphome_wifi_2_ssid
    password: !secret esphome_wifi_2_password 
  # manual_ip:
  #   static_ip: 192.168.2.106
  #   gateway: !secret esphome_network_gateway 
  #   subnet: !secret esphome_network_subnet 
  #   dns1: !secret esphome_network_dns1 
  ap:
    ssid: "Esphome FrontdoorCamera"
    password: !secret esphome_ap_password 

captive_portal: 

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_webserver_password

api:
  password: !secret esphome_api_password

logger:

ota:
  password: !secret esphome_ota_password

esp32_camera:
  name: Front Door Camera
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15 
  vertical_flip: false
  horizontal_mirror: false
  max_framerate: 1 fps
  idle_framerate: 0.001 fps

switch:
  - platform: restart
    name: "Front Door Camera Restart"