esphome:
  name: frontdoorcamera
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret doorbell_wifi_ssid
  password: !secret doorbell_wifi_password
 
logger:
 
api:
  password: !secret doorbell_ota_password

ota:
  password: !secret doorbell_ota_password
 
esp32_camera:
  name: Front Door Camera
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15 
  vertical_flip: false
  horizontal_mirror: false
  max_framerate: 1 fps
  idle_framerate: 0.3 fps
web_server:
  port: 80

switch:
  - platform: restart
    name: "Front Door Camera Restart"