esphome:
  name: hallway_1st_floor
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  networks:
  - ssid: !secret esphome_wifi_1_ssid
    password: !secret esphome_wifi_1_password
  - ssid: !secret esphome_wifi_2_ssid
    password: !secret esphome_wifi_2_password 
  # manual_ip:
  #   static_ip: 192.168.2.103
  #   gateway: !secret esphome_network_gateway 
  #   subnet: !secret esphome_network_subnet 
  #   dns1: !secret esphome_network_dns1  
  ap:
    ssid: "Esphome Hallway1StFloor"
    password: !secret esphome_ap_password 

captive_portal: 

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_webserver_password

api:
  password: !secret esphome_api_password

logger:

ota:
  password: !secret esphome_ota_password

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "hallway_1st_floor_switch" 
    on_press:
      then:
        - light.toggle: hallway_1st_floor_light
    on_release:
      then:
        - light.toggle: hallway_1st_floor_light

light:
  - platform: binary
    id: hallway_1st_floor_light
    name: "hallway_1st_floor_light"
    output: hallway_1st_floor_relay

output:
  - platform: gpio
    id: hallway_1st_floor_relay
    pin: GPIO4
 
switch:
  - platform: restart
    name: "Lights hallway 1st floor Restart"