esphome:
  name: kitchen
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  networks:
  - ssid: !secret esphome_wifi_1_ssid
    password: !secret esphome_wifi_1_password
  - ssid: !secret esphome_wifi_2_ssid
    password: !secret esphome_wifi_2_password 
  manual_ip:
    static_ip: 192.168.2.102
    gateway: !secret esphome_network_gateway 
    subnet: !secret esphome_network_subnet 
    dns1: !secret esphome_network_dns1  
  ap:
    ssid: "Esphome Kitchen"
    password: !secret esphome_ap_password 

captive_portal: 

web_server:
  port: 80
  auth:
    username: admin
    password: !secret esphome_webserver_password

api:
  password: !secret esphome_api_password

logger:

ota:
  password: !secret esphome_ota_password

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "kitchen_switch" 
    on_press:
      then:
        - light.toggle: kitchen_light
    on_release:
      then:
        - light.toggle: kitchen_light

light:
  - platform: binary
    id: kitchen_light
    name: "kitchen_light"
    output: kitchen_relay

output:
  - platform: gpio
    id: kitchen_relay
    pin: GPIO4
 
switch:
  - platform: restart
    name: "Kitchen Restart"