- id: 'TuinlichtAanBijZonsondergang'
  alias: 'TuinlichtAanBijZonsondergang'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.licht_in_tuin

- id: 'TuinlichtUitNaEenTijdje'
  alias: 'TuinlichtUitNaEenTijdje'
  trigger:
  - platform: time
    at: '23:30:00'
    # platform: sun
    # event: sunset
    # offset: "+02:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.licht_in_tuin

- id: 'TuinlichtAanVoorZonsopkomst'
  alias: 'TuinlichtAanVoorZonsopkomst' 
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.licht_in_tuin

- id: 'TuinlichtUitNaZonsopkomst'
  alias: 'TuinlichtUitNaZonsopkomst'
  trigger:
    platform: sun
    event: sunrise
    offset: "00:45:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.licht_in_tuin

- id: 'TuinNotificatie'
  alias: Poort of schuur open / niemand thuis
  condition: 
    condition: and
    conditions:
    - condition: template
      value_template: "{{ states('device_tracker.iphone_van_marleen') != 'home' }}"
    - condition: template
      value_template: "{{ states('device_tracker.iphone_van_kees') != 'home' }}"
  trigger:
  - platform: state
    entity_id: binary_sensor.poortdeur
    to: 'open'
    for:
      minutes: 2
  - platform: state
    entity_id: binary_sensor.schuurdeur
    to: 'open'
    for:
      minutes: 2
  action: 
   - service: notify.ios_iphone_van_kees
     data:
        title: "Schuur/poort open"
        message: "En er is niemand thuis!"
   - service: notify.ios_iphone_van_marleen
     data:
        title: "Schuur/poort open"
        message: "En er is niemand thuis!"

- id: 'RebootDafangEveryNight'
  alias: Reboot Dafang every night 
  trigger:
  - platform: time
    at: '12:10:00'
  action: 
    service: rest_command.reboot_dafang


# - id: backyard_motion_gif 
#   alias: backyard_motion_gif
#   trigger: 
#   - platform: state
#     entity_id: binary_sensor.dafang_motion_sensor 
#     to: 'on'
#   action:
#    - service: shell_command.backyard_gif 
     
- alias: New file alert
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: created
  action:
    service: notify.ios_iphone_van_kees
    data_template:
      title: New image captured!
      message: "Created {{ trigger.event.data.file }} in {{ trigger.event.data.folder }}"
      data:
        file: "{{ trigger.event.data.path }}"