- id: 'LightOnInHallway1stFloorWhenActivity'
  alias: Enable lights in hallway on the first floor when there is activity
  trigger:
  - platform: state
    entity_id: binary_sensor.0x00158d0002e2ab4d_occupancy 
    to: on
  - platform: state
    entity_id: binary_sensor.hallway_1st_floor_switch 
  condition: 
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action: 
  - service: light.turn_on
    data:
      entity_id: light.lights_hallway_1st_floor
  - service: timer.start
    data:
      entity_id: timer.hallway_1st_floor_lights_off_in

- alias: Turn off hallway 1st floor lights 3 minutes after trigger
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.hallway_1st_floor_lights_off_in
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.lights_hallway_1st_floor