- id: knop1
  alias: Living Room - Switch 1 (Eating)
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0001639d5a'
  condition:
    condition: template
    value_template: "{{ 'left' == trigger.payload_json.click }}"
  action:
    - service: homeassistant.turn_on
      entity_id: scene.Eating

- id: knop2
  alias: Living Room - Switch 2 (Evening)
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0001639d5a'
  condition:
    condition: template
    value_template: "{{ 'right' == trigger.payload_json.click }}"
  action:
    - service: homeassistant.turn_on
      entity_id: scene.evening

- id: knop3
  alias: Living Room - Switch 3 (Kitchen)
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0001710729'
  condition:
    condition: template
    value_template: "{{ 'left' == trigger.payload_json.click }}"
  action:
  - service: light.toggle
    data:
      entity_id: light.kitchen

- id: knop4
  alias:  Living Room - Switch 4 (All off)
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0001710729'
  condition:
    condition: template
    value_template: "{{ 'right' == trigger.payload_json.click }}"
  action:
    - service: homeassistant.turn_on
      entity_id: scene.living_room_lights_off  

- id: LightsOnAutoWhenMotion
  alias: Lights on when motion
  trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000222df56_occupancy
      to: 'on'
  condition: 
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: light.lampentafel
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: scene.Eating

- alias: Respond to button clicks
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d0001639d5a'
  condition:
    condition: template
    value_template: "{{ 'left' == trigger.payload_json.click }}"
  action:
   - service: notify.pushbullet
     data:
        title: "Button push"
        message: "Button push"