homeassistant:
  customize:
    light.shellydimmer2_40f5200033ef:
      friendly_name: Lights Hallway 1st floor
      icon: mdi:ceiling-light

    light.shellydimmer2_485519f2af15:
      friendly_name: Lights Jasmijn
      icon: mdi:ceiling-light
        
    timer.hallway_1st_floor_dimmer_lights_off_in:
      friendly_name: Hallway 1st floor lights off in

automation:  
  - id: "LightOnInHallway1stFloorWhenActivity"
    alias: Enable lights in hallway on the first floor when there is activity
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d0002e2ab4d_occupancy
        to: "on"
    action:
      - service: light.turn_on
        entity_id: light.shellydimmer2_40f5200033ef
        data_template:
          transition: 0
          brightness: >
            {% if now().hour > 21 %}30
            {% elif now().hour > 19 %}100
            {% elif now().hour < 7 %}30
            {% elif now().hour < 8 %}100
            {% else %}250
            {% endif %}
      - service: timer.start
        data:
          entity_id: timer.hallway_1st_floor_dimmer_lights_off_in

  - id: "LightOffInHallwayAfter3minutes"
    alias: Turn off the lights in the hallway 1st floor after x
    trigger:
      - platform: state
        entity_id: light.shellydimmer2_40f5200033ef
    action:
      - service: timer.start
        data:
          entity_id: timer.hallway_1st_floor_dimmer_lights_off_in

  - alias: Turn off hallway 1st floor lights 3 minutes after trigger
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.hallway_1st_floor_dimmer_lights_off_in
    action:
      service: light.turn_off
      data:
        transition: 0
        entity_id:
          - light.shellydimmer2_40f5200033ef 

  - alias: "Trigger timer when lights are turned on for room Jasmijn"
    trigger:
      platform: state
      entity_id: light.shellydimmer2_485519f2af15
      to: "on"
    action:
      - service: timer.start
        data:
          entity_id: timer.room_jasmijn_lights_off_in

  - alias: Turn off lights Jasmijn after 1hr
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.room_jasmijn_lights_off_in
    action:
      service: light.turn_off
      data:
        transition: 0
        entity_id:
          - light.shellydimmer2_485519f2af15 

timer:
  hallway_1st_floor_dimmer_lights_off_in:
    duration: "00:02:00"
  room_jasmijn_lights_off_in:
    duration: "01:00:00"
