homeassistant:
  customize:
    light.0x0017880108ca5f8e_light:
      friendly_name: Attic Ceiling 1

    light.0x001788010929be34_light:
      friendly_name: Attic Ceiling 2

    light.0x0017880108c51275_light:
      friendly_name: Attic Ceiling 3

    light.0x00124b002116c339_light:
      friendly_name: Attic LED Strip

    sensor.0x00158d0004a015c5_humidity:
      friendly_name: "Attic Humidity"
  
    sensor.0x00158d0004a015c5_pressure:
      friendly_name: "Attic Pressure"
      
    sensor.0x00158d0004a015c5_temperature:
      friendly_name: "Attic Temperature"

    binary_sensor.0x842e14fffe4b54f2_occupancy:
      friendly_name: "Attic Occupancy"

light:
  - platform: group
    name: Attic Ceiling & LED Strip
    entities:
      - light.0x0017880108ca5f8e_light
      - light.0x001788010929be34_light
      - light.0x0017880108c51275_light
      - light.0x00124b002116c339_light

automation:
  - alias: Motion Detection - Attic Light off
    trigger:
      platform: state
      entity_id: binary_sensor.0x842e14fffe4b54f2_occupancy
      to: "off"
      for: "00:30:00"
    action:
      - service: light.turn_off
        entity_id: light.attic_ceiling_led_strip
      - service: light.turn_off
        entity_id: light.elgato_key_light_air

  - alias: Motion Detection - Attic Light on
    trigger:
      platform: state
      entity_id: binary_sensor.0x842e14fffe4b54f2_occupancy
      to: "on"
    action:
      - service: light.turn_on
        entity_id: light.attic_ceiling_led_strip

  - alias: "Turn on attic lights via switch"
    trigger:
      - platform: state
        entity_id: binary_sensor.attic_switch
    action:
      - service: light.toggle
        entity_id: light.attic_ceiling_led_strip

  - alias: "Turn off the lights after working hours"
    trigger:
      platform: time
      at: "18:00:00"
    action:
      service: light.turn_off
      entity_id: light.attic_ceiling_led_strip

scene:
  - name: Colorfull Attic
    entities:
      light.0x0017880108ca5f8e_light:
        state: "on"
        xy_color: [0.14, 0.0]
        brightness: 255
      light.0x001788010929be34_light:
        state: "on"
        xy_color: [0.7, 0.3]
        brightness: 255
      light.0x0017880108c51275_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x00124b002116c339_light:
        state: "on"
        xy_color: [0.7, 0.3]
        brightness: 255

  - name: White Attic
    entities:
      light.0x0017880108ca5f8e_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x001788010929be34_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x0017880108c51275_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x00124b002116c339_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
