customize:
  light.0x0017880108ca5f8e_light:
    friendly_name: Attic Ceiling 1

  light.0x001788010929be34_light:
    friendly_name: Attic Ceiling 2

  light.0x0017880108c51275_light:
    friendly_name: Attic Ceiling 3

  light.0x00124b002116c339:
    friendly_name: Attic LED Strip

light:
  - platform: group
    name: Attic Ceiling & LED Strip
    id: attic_lights
    entities:
      - light.0x0017880108ca5f8e_light
      - light.0x001788010929be34_light
      - light.0x0017880108c51275_light
      - light.0x00124b002116c339

automation: 
  - alias: "Turn on attic lights via switch"
    trigger:
      - platform: state
        entity_id: binary_sensor.attic_switch  
    action:
      - service: light.toggle
        entity_id: light.attic_lights  

scene:
  - name: Colorfull Attic
    entities:
      light.0x0017880108ca5f8e_light:
        state: "on"
        xy_color: [0.14, 0.0]
        brightness: 255
      light.0x001788010929be34_light:
        state: "on"
        xy_color: [0.7, 0.3]
        brightness: 255
      light.0x0017880108c51275_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x00124b002116c339:
        state: "on"
        xy_color: [0.7, 0.3]
        brightness: 255

  - name: White Attic
    entities:
      light.0x0017880108ca5f8e_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x001788010929be34_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x0017880108c51275_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x00124b002116c339:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
