homeassistant:
  customize:
    light.0x0017880108ca5f8e_light:
      friendly_name: Attic Ceiling 1

    light.0x001788010929be34_light:
      friendly_name: Attic Ceiling 2

    light.0x0017880108c51275_light:
      friendly_name: Attic Ceiling 3

    light.0x00124b002116c339_light:
      friendly_name: Attic LED Strip

    sensor.0x00158d000a838163_humidity:
      friendly_name: "Attic Humidity"

    sensor.0x00158d000a838163_pressure:
      friendly_name: "Attic Pressure"

    sensor.0x00158d000a838163_temperature:
      friendly_name: "Attic Temperature"

    binary_sensor.0x842e14fffe4b54f2_occupancy:
      friendly_name: "Attic Occupancy"

    sensor.0x842e14fffe4b54f2_battery:
      friendly_name: "Attic - Occupancy Sensor Battery"

    sensor.0x00158d000a838163_battery:
      friendly_name: "Attic - Environment Sensor Battery"

    switch.0x84ba20fffe65529c:
      friendly_name: "Airco Power Plug (6)"
    sensor.0x84ba20fffe65529c_energy:
      friendly_name: "Airco Power Plug (6)"
    sensor.0x84ba20fffe65529c_power:
      friendly_name: "Airco Power Plug (6) - Power"

    switch.0x84ba20fffe6ac289:
      friendly_name: "WFH Area Plug (5)"
    sensor.0x84ba20fffe6ac289_energy:
      friendly_name: "WFH Area Plug (5)"
    sensor.0x84ba20fffe6ac289_power:
      friendly_name: "WFH Area Plug (5) - Power"

    switch.0x943469fffe7169b3:
      friendly_name: "WFH Laptop Plug (4)"
    sensor.0x943469fffe7169b3_energy:
      friendly_name: "WFH Laptop Plug (4)"
    sensor.0x943469fffe7169b3_power:
      friendly_name: "WFH Laptop Plug (4) - Power"

    switch.0x84ba20fffe6ac1ff:
      friendly_name: "Washing Machine Plug (7)"
    sensor.0x84ba20fffe6ac1ff_energy:
      friendly_name: "Washing Machine Plug (7)"
    sensor.0x84ba20fffe6ac1ff_power:
      friendly_name: "Washing Machine Plug (7) - Power"

light:
  - platform: group
    name: Attic Ceiling & LED Strip
    entities:
      - light.0x0017880108ca5f8e_light
      - light.0x001788010929be34_light
      - light.0x0017880108c51275_light
      - light.0x00124b002116c339_light

input_boolean:
  attic_keep_on_requested:
    name: "Attic Keep On Requested"
    initial: false

automation:
  - alias: "Attic Auto-off Notification"
    trigger:
      trigger: state
      entity_id: binary_sensor.0x842e14fffe4b54f2_occupancy
      to: "off"
      for: "01:00:00"
    condition:
      - condition: state
        entity_id: device_tracker.iphone_kees
        state: "home"
      - condition: state
        entity_id: switch.0x943469fffe7169b3
        state: "on"
    action:
      - action: notify.mobile_app_iphone_kees
        data:
          message: "Attic lights and airco will turn off in 15 minutes. Tap to keep on."
          data:
            tag: "attic_auto_off"
            actions:
              - action: "KEEP_ATTIC_ON"
                title: "Keep On"
                icon: "sfsymbols:lightbulb.fill"
      - delay: "00:15:00"
      - condition: template
        value_template: "{{ not states('input_boolean.attic_keep_on_requested') == 'on' }}"
      - action: light.turn_off
        entity_id: light.attic_ceiling_led_strip
      - action: light.turn_off
        entity_id: light.elgato_key_light_air
      - action: media_player.media_stop
        target:
          entity_id: media_player.sonos_sonos_attic
      - action: climate.turn_off
        target:
          entity_id: climate.airco_zolder
      - action: switch.turn_off
        entity_id: switch.0x943469fffe7169b3
      - action: notify.mobile_app_iphone_kees
        data:
          message: "clear_notification"
          data:
            tag: "attic_auto_off"

  - alias: Motion Detection - Attic Light on
    trigger:
      trigger: state
      entity_id: binary_sensor.0x842e14fffe4b54f2_occupancy
      to: "on"
    action:
      - action: light.turn_on
        entity_id: light.attic_ceiling_led_strip
      - action: input_boolean.turn_off
        entity_id: input_boolean.attic_keep_on_requested

  - alias: "Turn on attic lights via switch"
    trigger:
      - trigger: state
        entity_id: binary_sensor.attic_switch
    action:
      - action: light.toggle
        entity_id: light.attic_ceiling_led_strip

  - alias: "Turn off the lights after working hours"
    trigger:
      trigger: time
      at: "18:00:00"
    action:
      - action: light.turn_off
        entity_id: light.attic_ceiling_led_strip

  - alias: "Ask to turn off power"
    trigger:
      trigger: time
      at: "18:00:00"
    condition:
      - condition: state
        entity_id: switch.0x943469fffe7169b3
        state: "on"
    action:
      - action: notify.mobile_app_iphone_kees
        data:
          message: "Turn of power at WFH plug?"
          data:
            actions:
              - action: "TURN_OFF_WFH_POWER"
                title: "Turn off"
                icon: "sfsymbols:person.crop.circle.badge.exclam"

  - alias: "Turn off WFH plug notification"
    trigger:
      - trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: "TURN_OFF_WFH_POWER"
    action:
      - action: homeassistant.turn_off
        entity_id: switch.0x943469fffe7169b3

  - alias: "Keep Attic On Notification Handler"
    trigger:
      - trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: "KEEP_ATTIC_ON"
    action:
      - action: input_boolean.turn_on
        entity_id: input_boolean.attic_keep_on_requested
      - action: notify.mobile_app_iphone_kees
        data:
          message: "clear_notification"
          data:
            tag: "attic_auto_off"

  - alias: Start Call on Laptop
    condition: 
      - condition: template
        value_template: "{{ states('device_tracker.iphone_kees') == 'home' }}"
    trigger:
      - trigger: state
        entity_id: sensor.msteams_kees_status
        to: "InACall"
      - trigger: state
        entity_id: sensor.msteams_kees_status
        to: "InAMeeting"
      - trigger: state
        entity_id: sensor.msteams_kees_status
        to: "InAConferenceCall"
      - trigger: state
        entity_id: sensor.msteams_kees_status
        to: "Presenting"
    action:
      - action: scene.turn_on
        target:
          entity_id: scene.colorfull_attic
      - action: light.turn_on
        entity_id: light.elgato_key_light_air
      - action: media_player.volume_mute
        data:
          is_volume_muted: true
        target:
          entity_id: media_player.sonos_sonos_attic

  - alias: End Call on Laptop
    trigger:
      - trigger: state
        entity_id: sensor.msteams_kees_status
        from: "InACall"
      - trigger: state
        entity_id: sensor.msteams_kees_status
        from: "InAMeeting"
      - trigger: state
        entity_id: sensor.msteams_kees_status
        from: "InAConferenceCall"
      - trigger: state
        entity_id: sensor.msteams_kees_status
        from: "Presenting"
    action:
      - action: light.turn_off
        entity_id: light.elgato_key_light_air
      - action: media_player.volume_mute
        data:
          is_volume_muted: false
        target:
          entity_id: media_player.sonos_sonos_attic

scene:
  - name: Colorfull Attic
    entities:
      light.0x0017880108ca5f8e_light:
        state: "on"
        xy_color: [0.14, 0.0]
        brightness: 255
      light.0x001788010929be34_light:
        state: "on"
        xy_color: [0.7, 0.3]
        brightness: 255
      light.0x0017880108c51275_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x00124b002116c339_light:
        state: "on"
        xy_color: [0.7, 0.3]
        brightness: 255

  - name: White Attic
    entities:
      light.0x0017880108ca5f8e_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x001788010929be34_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x0017880108c51275_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
      light.0x00124b002116c339_light:
        state: "on"
        xy_color: [0.3, 0.3]
        brightness: 255
  - name: PowerSavingOn
    entities:
      switch.0x943469fffe716cf4:
        state: "off"
      switch.0x943469fffe7169b3:
        state: "off"
