homeassistant:

axis:
  - host: !secret m4308_host
    username: !secret m4308_username
    password: !secret m4308_password
    port: 80
    include:
      - camera
    camera:
      - name: "M4308 Main Stream"
        video_source: 0
      - name: "M4308 Secondary Stream" 
        video_source: 1 

# switch:
#   - platform: xiaomi_miio
#     name: Licht in tuin
#     host: 192.168.1.32 #chuangmi-plug-v3_miio71262865
#     token:  !secret xiaomi_plug_tuin
#     model: chuangmi.plug.v2

automation:
  - id: 'TuinlichtAanBijZonsondergang'
    alias: 'TuinlichtAanBijZonsondergang'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.0xe0798dfffeb91086

  - id: 'TuinlichtUitNaEenTijdje'
    alias: 'TuinlichtUitNaEenTijdje'
    trigger:
    - platform: time
      at: '23:30:00'
      # platform: sun
      # event: sunset
      # offset: "+02:00:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.0xe0798dfffeb91086

  - id: 'TuinlichtAanVoorZonsopkomst'
    alias: 'TuinlichtAanVoorZonsopkomst' 
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:45:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.0xe0798dfffeb91086

  - id: 'TuinlichtUitNaZonsopkomst'
    alias: 'TuinlichtUitNaZonsopkomst'
    trigger:
      platform: sun
      event: sunrise
      offset: "00:45:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.0xe0798dfffeb91086
  
          

          