homeassistant:
  customize: 
    light.bathroom_main_light:
      friendly_name: Bathroom - Main Light 
    binary_sensor.bathroom_main_light:
      friendly_name: Bathroom - Main Light Switch

    light.0x000b57fffed598bc_light:
      friendly_name: Bathroom - Mirror Light
    sensor.0x000b57fffed598bc_linkquality: 
      friendly_name: Bathroom - Mirror Light Linkquality 

    sensor.0x00158d0001f5358e_pressure:
      friendly_name: Bathroom - Environment Sensor Pressure 
    sensor.0x00158d0001f5358e_humidity:
      friendly_name: Bathroom - Environment Sensor Humidity 
    sensor.0x00158d0001f5358e_temperature:
      friendly_name: Bathroom - Environment Sensor Temperature 
    sensor.0x00158d0001f5358e_battery:
      friendly_name: Bathroom - Environment Sensor Battery 
      

    binary_sensor.0x00158d0002e2e35e_occupancy:
      friendly_name: Bathroom - Occupancy
    sensor.0x00158d0002e2e35e_battery:
      friendly_name: Bathroom - Occupancy Battery 
    sensor.0x00158d0002e2e35e_illuminance:
      friendly_name: Bathroom - Occupancy Illuminance 
    sensor.0x00158d0002e2e35e_linkquality:
      friendly_name: Bathroom - Occupancy Linkquality

    binary_sensor.0x00158d0003120fb3_contact:
      friendly_name: Bathroom - Door Contact 
    sensor.0x00158d0003120fb3_battery:
      friendly_name: Bathroom - Door Battery 
    sensor.0x00158d0003120fb3_linkquality:
      friendly_name: Bathroom - Door Link Quality

light:
  - platform: group
    name: Bathroom Lights
    entities:
      - light.0x000b57fffed598bc_light
      - light.bathroom_main_light
      
automation:
  - alias: "Switch bathroom lights when switch is used"
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_main_switch
    action:
      - service: light.toggle
        entity_id: light.bathroom_lights
        data_template:
          brightness: "200" 

  - alias: "Turn on bathroom mirror light when door is opened"
    trigger: 
    - platform: state
      entity_id: binary_sensor.0x00158d0003120fb3_contact
      to: "on"
    action:
      - service: light.turn_on
        entity_id: light.0x000b57fffed598bc_light
        data_template:
          brightness: >
            {% if now().hour > 20 %}100
            {% elif now().hour < 5 %}50
            {% elif now().hour < 8 %}100
            {% else %}200
            {% endif %} 