automation:
  - id: "DoorbellNotificationWithImage"
    alias: Doorbell Notification With Image
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button_2
        to: "on"
    action:
      - service:  camera.snapshot
        target:
          entity_id: camera.front_door_camera
        data:
          filename: '/media/local/front_door_latest.png'
      - service: notify.phones_kees_marleen
        data:
          title: "Er wordt aan de deur gebeld"
          message: "Wie zou dat zijn?"
          data:
            image: "/media/local/front_door_latest.png"
            push: 
              interruption-level: critical 
            entity_id: camera.front_door_camera
      - service:  camera.snapshot
        target:
          entity_id: camera.front_door_camera
        data:
          filename: '/media/local/{{ now().strftime("%Y%m%d-%H%M%S") }}.png'

  - id: "DoorbellNotificationViaSonos"
    alias: Doorbell Notification via Sonos
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button_2
        to: "on"
    action: 
      - service: script.sonos_say
        data:
          sonos_entity: media_player.sonos_beam
          volume: 0.5
          message: "Er wordt aan de deur gebeld!"

  - id: "DoorbellSoundSilendAtNight"
    alias: DoorbellSoundSilendAtNight
    trigger:
      - platform: time
        at: "18:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.doorbell_buzzer_enabled_2

  - id: "DoorbellSoundBackToNormall"
    alias: DoorbellSoundBackToNormall
    trigger:
      - platform: time
        at: "07:00:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.doorbell_buzzer_enabled_2
