automation:
  - id: "DoorbellNotificationWithImage"
    alias: Doorbell Notification With Image
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button_2
        to: "on"
    action:
      - service:  camera.record
        target:
          entity_id: camera.front_door_camera
        data:
          filename: '/media/local/latest_doorbell.mp4'
          duration: 3
      - service: notify.phones_kees_marleen
        data_template:
          title: "Er wordt aan de deur gebeld"
          message: "Wie zou dat zijn?"
          data:
            video: "/media/local/latest_doorbell.mp4"
            attachment: 
              lazy: true
            push: 
              thread-id: "doorbell"
              category: camera
            entity_id: camera.front_door_latest

  - id: "DoorbellNotificationViaSonos"
    alias: Doorbell Notification via Sonos
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button_2
        to: "on"
    action: 
      - service: script.sonos_say
        data:
          sonos_entity: media_player.woonkamer
          volume: 0.5
          message: "Er wordt aan de deur gebeld!"

  - id: "DoorbellSoundSilendAtNight"
    alias: DoorbellSoundSilendAtNight
    trigger:
      - platform: time
        at: "18:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.doorbell_buzzer_enabled_2

  - id: "DoorbellSoundBackToNormall"
    alias: DoorbellSoundBackToNormall
    trigger:
      - platform: time
        at: "07:00:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.doorbell_buzzer_enabled_2
