automation:
  - id: "DoorbellNotificationWithImage"
    alias: Doorbell Notification With Image
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button
        to: "on"
    action:
      - service: script.take_front_door_snaps
      - service: notify.pushbullet
        data_template:
          title: "Er wordt aan de deur gebeld"
          message: "Wie zou dat zijn!?"
          data:
            # file_url: "https://schollaartthuis.duckdns.org:8123/local/front-door/front-door-latest.gif"
            file: "/share/motion/front-door/front-door-latest.gif"
            file_type: "image/gif"
      - service: notify.ios_marleen_marleen01
        data_template:
          title: "Er wordt aan de deur gebeld"
          message: "Wie zou dat zijn?"
          data:
            url: "https://schollaartthuis.duckdns.org:8123/{{ states.camera.front_door_latest.attributes.entity_picture }}" 
            attachment:
              url: "https://schollaartthuis.duckdns.org:8123/{{ states.camera.front_door_latest.attributes.entity_picture }}" 
              content-type: gif
              hide-thumbnail: false

  - id: "DoorbellNotificationViaSonos"
    alias: Doorbell Notification via Sonos
    trigger:
      - platform: state
        entity_id: binary_sensor.doorbell_button
        to: "on"
    action: 
      - service: script.sonos_say
        data:
          sonos_entity: media_player.woonkamer
          volume: 0.5
          message: "Er wordt aan de deur gebeld!"

  - id: "DoorbellSoundSilendAtNight"
    alias: DoorbellSoundSilendAtNight
    trigger:
      - platform: time
        at: "18:30:00"
    action:
      service: homeassistant.turn_off
      entity_id: switch.doorbell_buzzer_enabled

  - id: "DoorbellSoundBackToNormall"
    alias: DoorbellSoundBackToNormall
    trigger:
      - platform: time
        at: "07:00:00"
    action:
      service: homeassistant.turn_on
      entity_id: switch.doorbell_buzzer_enabled
