automation:
  - id: "VoordeurNotificatieNiemandThuis"
    alias: Voordeur of schuur open / niemand thuis
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.iphone_van_marleen') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.iphone_kees') != 'home' }}"
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000208e0e0_contact
        to: "on"
        for:
          seconds: 2
    action:
      - service:  camera.record
        target:
          entity_id: camera.front_door_camera
        data:
          filename: '/media/front_door_latest.png'
          duration: 3
      - service: notify.phones_kees_marleen
        data_template:
          title: "Er wordt aan de deur gebeld"
          message: "Wie zou dat zijn?"
          data:
            video: "/media/front_door_latest.png"
            attachment: 
              lazy: true
            push: 
              thread-id: "doorbell"
              category: camera
            entity_id: camera.front_door_latest

  - id: "VoordeurNotificatieTeLangOpen"
    alias: Voordeur te lang open
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000208e0e0_contact
        to: "on"
        for:
          minutes: 2
    action:
      - service: script.take_front_door_snaps
      - service: notify.phones_kees_marleen
        data_template:
          title: "Voordeur meer dan 2 minuten open"
          message: "Misschien vergeten dicht te doen?"
          data:
            url: "https://schollaartthuis.duckdns.org:8123/{{ states.camera.front_door_latest.attributes.entity_picture }}"
            attachment:
                url: "https://schollaartthuis.duckdns.org:8123/{{ states.camera.front_door_latest.attributes.entity_picture }}"
                content-type: jpg
                hide-thumbnail: false
            push: 
              thread-id: "front_door"
              category: camera
            entity_id: camera.front_door_latest

  - id: "VoordeurOpenDicht"
    alias: Voordeur open of dicht
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000208e0e0_contact
        to: "on"
    action:
      - service:  camera.record
        target:
          entity_id: camera.front_door_camera
        data:
          filename: '/tmp/{{ entity_id.name }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
 
homeassistant:
  customize:
    binary_sensor.0x00158d000208e0e0_contact:
      friendly_name: Front door

    binary_sensor.0x00158d000208e0e0_battery:
      friendly_name: Front door Battery
