automation:
  - alias: Daily reset goodnight routine
    id: daily_reset_goodnight_routine
    trigger:
      platform: time
      at: "07:30:00"
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.google_goodnight_routine

  - id: google_goodnight_routine
    trigger:
      - platform: state
        entity_id: input_boolean.google_goodnight_routine
        to: "on"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.staandelamp
          - light.bank 
          - light.shellydimmer2_e8db84d2e4d6
          - light.0x00158d0004f819c9_light
          - light.shellydimmer2_e8db84d2ed82
      - service: light.turn_on
        entity_id: light.shellydimmer2_e8db84d2ed82
        data_template:
          brightness: "10"
      - delay: "00:02"
      - service: light.turn_off
        entity_id: 
        - switch.0xe0798dfffeb91086
        - switch.0x943469fffe716cf4

          
input_boolean:
  google_goodnight_routine:
    initial: off

google_assistant:
  project_id: home-assistant-72f48
  service_account: !include ../google-service-account.json
  expose_by_default: false
  exposed_domains:
    - switch
    - light
    - climate
  entity_config:
    input_boolean.google_goodnight_routine:
      name: Goodnight
      expose: true
    light.0x90fd9ffffe2b5781_light:
      name: Toilet
      expose: true
      aliases:
        - wc
        - w.c.
    light.hall_light:
      name: Hal
      expose: true
      aliases:
        - Hal beneden
    light.attic:
      name: Zolder
    light.bank:
      name: Bank
      expose: true
      aliases:
        - Raam
    light.hallway_1st_floor_dimmer_light:
      name: Hal boven
      expose: true
      aliases:
        - Hal eerste verdieping
        - Hal eerste etage
    light.shellydimmer2_e8db84d2e4d6:
      name: Keuken
      expose: true
    light.shellydimmer2_e8db84d2ed82:
      name: Tafel
      expose: true
      aliases:
        - Eettafel
    light.staandelamp:
      name: Staande lamp
      expose: true
      aliases:
        - Staand
        - Hoek van de kamer
    scene.eating:
      name: eten
      expose: true
      aliases:
        - etenstijd
    scene.evening:
      name: savonds
      expose: true
      aliases:
        - avonds
        - avond
    climate.thermostat:
      name: Toon
      expose: true
    switch.doorbell_buzzer_enabled_2:
      name: Deurbel
      expose: true
      aliases:
        - Deurbel geluid 
