homeassistant:
  customize:
    light.bank:
      friendly_name: Couch lamp
      icon: mdi:lamp

    light.staandelamp:
      friendly_name: Standing lamp
      icon: mdi:floor-lamp

    light.shellydimmer2_e8db84d2e4d6:
      friendly_name: Kitchen
      icon: mdi:ceiling-light

    light.shellydimmer2_e8db84d2ed82:
      friendly_name: Table Lights
      icon: mdi:string-lights

    binary_sensor.0x00158d000222df56_occupancy:
      friendly_name: Living Room - Motion

    sensor.0x00158d000222df56_illuminance:
      friendly_name: Living Room - Illuminance

    sensor.0x00158d000222df56_battery:
      friendly_name: Living Room - Motion Sensor Battery

    sensor.0x00158d0001639d5a_click:
      friendly_name: Living Room - Switch Left

    sensor.0x00158d0001639d5a_battery:
      friendly_name: Living Room - Switch Left Battery

    sensor.0x00158d0001710729_click:
      friendly_name: Living Room - Switch Right

    sensor.0x00158d0001710729_battery:
      friendly_name: Living Room - Switch Right Battery

    binary_sensor.0x00158d00027743b7_water_leak:
      friendly_name: Coffee Machine water reservoir

    sensor.0x00158d0004a0166e_humidity:
      friendly_name: "Living Room - Humidity"

    sensor.0x00158d0004a0166e_pressure:
      friendly_name: "Living Room - Pressure"

    sensor.0x00158d0004a0166e_temperature:
      friendly_name: "Living Room - Temperature"

    light.0x00158d00058d0cdf:
      friendly_name: "Living Room - Couch Bulb"
      icon: mdi:desk-lamp

    switch.0x00158d0004f819c9:
      friendly_name: "Living Room - Cabinet Lights"
      icon: mdi:file-cabinet
    
    switch.0xb4e3f9fffea52bae:
      friendly_name: "Aquarium Lights"
      icon: mdi:fish

    switch.0x84ba20fffe6ac2c7:
      friendly_name: "Couch Corner Plug (1)"
    sensor.0x84ba20fffe6ac2c7_energy:
      friendly_name: "Couch Corner Plug (1)"

    sensor.0x943469fffe716cf4:  
      friendly_name: "TV & Xbox Plug (2)"
    sensor.0x943469fffe716cf4_energy:  
      friendly_name: "TV & Xbox Plug (2)"

    sensor.0x943469fffe716b2c:  
      friendly_name: "Fridge Plug (3)"
      
    sensor.0x943469fffe716b2c_energy:  
      friendly_name: "Fridge Plug (3)"


  
light:
  # - platform: xiaomi_miio #ok
  #   name: staandelamp
  #   host: philips-light-bulb_miio61632965.localdomain
  #   token: !secret staandelamp_token
  # - platform: xiaomi_miio #ok
  #   name: bank
  #   host: philips-light-bulb_miio61510856.localdomain
  #   token: !secret bank_token
  # - platform: xiaomi_miio
  #   name: tafel1
  #   host: philips-light-bulb_miio61623717.localdomain
  #   token: !secret tafel1_token
  # - platform: xiaomi_miio #ok
  #   name: tafel2
  #   host: philips-light-bulb_miio61511979.localdomain
  #   token: !secret tafel2_token
  # - platform: xiaomi_miio
  #   name: tafel3
  #   host: philips-light-bulb_miio60379202.localdomain
  #   token: !secret tafel3_token
  # - platform: group
  #   name: LampenTafel
  #   entities:
  #     - light.tafel1
  #     - light.tafel2
  #     - light.tafel3
  - platform: group
    name: Hall Light
    entities:
      - light.0x90fd9ffffe10c5d1_light
      - light.0x90fd9ffffe135ab2_light
  - platform: switch    
    name: "0x00158d0004f819c9_light" 
    entity_id: switch.0x00158d0004f819c9
  - platform: group
    name: Livingroom
    entities:
      - light.staandelamp
      - light.bank
      - light.shellydimmer2_e8db84d2ed82
      - light.shellydimmer2_e8db84d2e4d6
      - light.0x00158d00058d0cdf
      - light.0x00158d0004f819c9_light
scene:
  - name: Evening
    entities: 
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 29
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 25
      light.0x00158d00058d0cdf:
        state: "on"
        brightness: 30
      switch.0x00158d0004f819c9:
        state: "on"

  - name: Eating
    entities: 
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 125
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 30
      light.0x00158d00058d0cdf:
        state: "on"
        brightness: 50
      switch.0x00158d0004f819c9:
        state: "off"
        
  - name: Cooking
    entities: 
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 30
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 230 
      light.0x00158d00058d0cdf:
        state: "on"
        brightness: 40
      switch.0x00158d0004f819c9:
        state: "off"

  - name: Maximum
    entities:
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 255
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 255 
      light.0x00158d00058d0cdf:
        state: "on"
        brightness: 255
      switch.0x00158d0004f819c9:
        state: "on"

  - name: living_room_lights_off
    entities:
      light.shellydimmer2_e8db84d2ed82:
        state: "off" 
      light.shellydimmer2_e8db84d2e4d6:
        state: "off"
      light.0x00158d00058d0cdf:
        state: "off"
      switch.0x00158d0004f819c9:
        state: "off"

automation:
  - alias: Evening Scene
    id: evening_scene
    trigger:
      platform: time
      at: "18:30:00"
    condition:
      - condition: state
        entity_id: light.shellydimmer2_e8db84d2ed82
        state: "on"
      - condition: state
        entity_id: "group.everyone"
        state: "home"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.evening
        data:
          transition: 20

  - id: 'Cooking Scene Living room'
    alias: 'Cooking Scene Living room'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    condition:
      - condition: state
        entity_id: light.shellydimmer2_e8db84d2e4d6
        state: "off"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.cooking
        data:
          transition: 20
 

  - id: 'Eating Scene Living room'
    alias: 'Eating Scene Living room'
    trigger:
      platform: time
      at: "17:15:00"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.eating
        data:
          transition: 20 

  - id: knop1
    alias: Living Room - Switch 1 (Eating)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001639d5a_click
        to: "left"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.Eating

  - id: knop2
    alias: Living Room - Switch 2 (Evening)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001639d5a_click
        to: "right"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.evening

  - id: knop3
    alias: Living Room - Switch 3 (Kitchen)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001710729_click
        to: "left"
    action:
      - service: light.toggle
        data:
          entity_id: light.shellydimmer2_e8db84d2e4d6

  - id: knop4
    alias: Living Room - Switch 4 (All off)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001710729_click
        to: "right"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.living_room_lights_off

  - id: knop5
    alias: Living Room - Switch 5
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001710729_click
        to: "both"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.google_goodnight_routine 

  - id: LightsOnAutoWhenMotion
    alias: Lights on when motion
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000222df56_occupancy
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: light.shellydimmer2_e8db84d2e4d6
          state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.eating

  - alias: Auto off
    id: off_scene_automation
    trigger:
      platform: time
      at: "22:15:00"
    condition:
      - condition: state
        entity_id: "group.everyone"
        state: "not_home"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.living_room_lights_off

  - alias: Aquarium Lights on
    id: aquarium_lights_on
    trigger:
      - platform: time
        at: "15:30:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.0xb4e3f9fffea52bae

  - alias: Aquarium Lights off
    id: aquarium_lights_off
    trigger:
      - platform: time
        at: "21:30:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.0xb4e3f9fffea52bae

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
      - service: sonos.snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: sonos.unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      - service: tts.google_translate_say
        data_template:
          entity_id: "{{ sonos_entity }}"
          message: "{{ message }}"
      - delay: "00:00:08"
      - service: sonos.restore
        data_template:
          entity_id: "{{ sonos_entity }}"

climate:
  - platform: toon_climate
    host: eneco-001-039306.localdomain

sensor:
  - platform: toon_smartmeter
    host: eneco-001-039306.localdomain
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - heat
