homeassistant:
  customize:
    light.bank:
      friendly_name: Couch lamp
      icon: mdi:lamp

    light.staandelamp:
      friendly_name: Standing lamp
      icon: mdi:floor-lamp

    light.shellydimmer2_e8db84d2e4d6:
      friendly_name: Kitchen
      icon: mdi:ceiling-light

    light.shellydimmer2_e8db84d2ed82:
      friendly_name: Table Lights
      icon: mdi:string-lights

    binary_sensor.0x00158d000222df56_occupancy:
      friendly_name: Living Room - Motion

    sensor.0x00158d000222df56_illuminance:
      friendly_name: Living Room - Illuminance

    sensor.0x00158d000222df56_battery:
      friendly_name: Living Room - Motion Sensor Battery

    sensor.0x00158d0001639d5a_click:
      friendly_name: Living Room - Switch Left

    sensor.0x00158d0001639d5a_battery:
      friendly_name: Living Room - Switch Left Battery

    sensor.0x00158d0001710729_click:
      friendly_name: Living Room - Switch Right

    sensor.0x00158d0001710729_battery:
      friendly_name: Living Room - Switch Right Battery

    binary_sensor.0x00158d00027743b7_water_leak:
      friendly_name: Coffee Machine water reservoir

    sensor.0x00158d0004a0166e_humidity:
      friendly_name: "Living Room - Humidity"

    sensor.0x00158d0004a0166e_pressure:
      friendly_name: "Living Room - Pressure"

    sensor.0x00158d0004a0166e_temperature:
      friendly_name: "Living Room - Temperature"

    # light.0x00158d00058d0cdf:
    #   friendly_name: "Living Room - Couch Bulb"
    #   icon: mdi:desk-lamp

    switch.0x00158d0004f819c9:
      friendly_name: "Living Room - Cabinet Lights"
      icon: mdi:file-cabinet
    
    switch.0xb4e3f9fffea52bae:
      friendly_name: "Christmass tree Lights"
      icon: mdi:tree

    switch.0x84ba20fffe6ac2c7:
      friendly_name: "Couch Corner Plug (1)"
    sensor.0x84ba20fffe6ac2c7_energy:
      friendly_name: "Couch Corner Plug (1)"
    sensor.0x84ba20fffe6ac2c7_power:
      friendly_name: "Couch Corner Plug (1) - Power" 

    switch.0x943469fffe716cf4:  
      friendly_name: "TV & Xbox Plug (2)"
    sensor.0x943469fffe716cf4_energy:  
      friendly_name: "TV & Xbox Plug (2)"
    sensor.0x943469fffe716cf4_power:  
      friendly_name: "TV & Xbox Plug (2) - Power"

    switch.0x943469fffe716b2c:  
      friendly_name: "Fridge Plug (3)" 
    sensor.0x943469fffe716b2c_energy:  
      friendly_name: "Fridge Plug (3)"
    sensor.0x943469fffe716b2c_power:  
      friendly_name: "Fridge Plug (3) - Power"
 

    switch.shellyplus1_80646fdaacf0_switch_0:
      friendly_name: Light trapkast

    binary_sensor.0x00158d000ad82338_contact:
      friendly_name: Trapkast deur

    light.0x00158d00097057c6:
      friendly_name: Couch bulb
      
input_boolean:
  fish_got_food:
    initial: off

light: 
  - platform: group
    name: Hall Light
    entities:
      - light.0x90fd9ffffe10c5d1_light
      - light.0x90fd9ffffe135ab2_light
  - platform: switch    
    name: "0x00158d0004f819c9_light" 
    entity_id: switch.0x00158d0004f819c9
  - platform: group
    name: Livingroom
    entities:
      - light.staandelamp
      - light.bank
      - light.shellydimmer2_e8db84d2ed82
      - light.shellydimmer2_e8db84d2e4d6
      - light.0x00158d00058d0cdf
      - light.0x00158d0004f819c9_light
      - light.0x00158d00097057c6
      - switch.0xb4e3f9fffea52bae
      
# home_connect_alt:
#   client_id: !secret home_connect_client_id
#   client_secret: !secret home_connect_client_secret 

scene:
  - name: Evening
    entities: 
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 29
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 25 
      switch.0x00158d0004f819c9:
        state: "on"
      light.0x00158d00097057c6:
        state: "on"
        brightness: 25 
      switch.0xb4e3f9fffea52bae:
        state: "on"

  - name: Eating
    entities: 
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 125
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 30 
      switch.0x00158d0004f819c9:
        state: "off"
      light.0x00158d00097057c6:
        state: "on"
        brightness: 25 
      switch.0xb4e3f9fffea52bae:
        state: "on"
        
  - name: Cooking
    entities: 
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 30
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 230  
      switch.0x00158d0004f819c9:
        state: "off"
      light.0x00158d00097057c6:
        state: "on"
        brightness: 25 
      switch.0xb4e3f9fffea52bae:
        state: "on"

  - name: Maximum
    entities:
      light.shellydimmer2_e8db84d2ed82:
        state: "on"
        brightness: 255
      light.shellydimmer2_e8db84d2e4d6:
        state: "on"
        brightness: 255  
      switch.0x00158d0004f819c9:
        state: "on"
      light.0x00158d00097057c6:
        state: "on"
        brightness: 255
      switch.0xb4e3f9fffea52bae:
        state: "on"

  - name: living_room_lights_off
    entities:
      light.shellydimmer2_e8db84d2ed82:
        state: "off" 
      light.shellydimmer2_e8db84d2e4d6:
        state: "off" 
      switch.0x00158d0004f819c9:
        state: "off"
      light.0x00158d00097057c6:
        state: "off"
      switch.0xb4e3f9fffea52bae:
        state: "off"

automation:
  - alias: Evening Scene
    id: evening_scene
    trigger:
      platform: time
      at: "18:30:00"
    condition:
      - condition: state
        entity_id: light.shellydimmer2_e8db84d2ed82
        state: "on"
      - condition: state
        entity_id: "group.everyone"
        state: "home"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.evening
        data:
          transition: 20

  - id: 'Cooking Scene Living room'
    alias: 'Cooking Scene Living room'
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    condition:
      - condition: state
        entity_id: light.shellydimmer2_e8db84d2e4d6
        state: "off"
      - condition: state
        entity_id: "group.everyone"
        state: "home"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.cooking
        data:
          transition: 20
 

  - id: 'Eating Scene Living room'
    alias: 'Eating Scene Living room'
    trigger:
      platform: time
      at: "17:15:00"
    condition:
      - condition: state
        entity_id: "group.everyone"
        state: "home"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.eating
        data:
          transition: 20 

  - id: knop1
    alias: Living Room - Switch 1 (Eating)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001639d5a_click
        to: "left"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.Eating

  - id: knop2
    alias: Living Room - Switch 2 (Evening)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001639d5a_click
        to: "right"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.evening

  - id: knop3
    alias: Living Room - Switch 3 (Kitchen)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001710729_click
        to: "left"
    action:
      - service: light.toggle
        data:
          entity_id: light.shellydimmer2_e8db84d2e4d6

  - id: knop4
    alias: Living Room - Switch 4 (All off)
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001710729_click
        to: "right"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.living_room_lights_off

  - id: knop5
    alias: Living Room - Switch 5
    trigger:
      - platform: state
        entity_id: sensor.0x00158d0001710729_click
        to: "both"
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.google_goodnight_routine 
      - service: homeassistant.turn_off
        entity_id: switch.0x943469fffe716cf4

  - id: LightsOnAutoWhenMotion
    alias: Lights on when motion
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000222df56_occupancy
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: light.shellydimmer2_e8db84d2e4d6
          state: "off"
    action:
      - service: homeassistant.turn_on
        entity_id: scene.eating

  - id: TVXBoxPlugOnWhenMotion
    alias: TV 7 XBOX plug on when motion
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000222df56_occupancy
        to: "on"
    action:
      - service: homeassistant.turn_on
        entity_id: switch.0x943469fffe716cf4

  - alias: Auto off
    id: off_scene_automation
    trigger:
      platform: time
      at: "22:15:00"
    condition:
      - condition: state
        entity_id: "group.everyone"
        state: "not_home"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.living_room_lights_off
      - service: homeassistant.turn_off
        entity_id: switch.0x943469fffe716cf4


  - alias: Confirm Thermostat
    id: confirm_thermostat
    trigger:
      - platform: state
        entity_id: climate.toon_thermostat
        attribute: hvac_action
        to: heating
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.iphone_van_marleen') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.iphone_kees') != 'home' }}"
    action:
    - service: notify.phones_kees_marleen
      data:
        message: "CV gaat aan en er is niemand thuis"
        data:
          actions:
            - action: "HEATING_AWAY"
              title: "Away"
              icon: "sfsymbols:person.crop.circle.badge.exclam"
            - action: "HEATING_COMFORT"
              title: "Comfort"
              icon: "sfsymbols:flame"
            - action: "HEATING_HOME"
              title: "Home"
              icon: "sfsymbols:house.fill"

  - alias: "Heating away"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "HEATING_AWAY"
    action:
      - service: climate.set_preset_mode
        entity_id: climate.toon_thermostat
        data:
          preset_mode: "away"

  - alias: "Heating comfort"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "HEATING_COMFORT"
    action:
      - service: climate.set_preset_mode
        entity_id: climate.toon_thermostat
        data:
          preset_mode: "comfort"

  - alias: "Heating home"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "HEATING_HOME"
    action:
      - service: climate.set_preset_mode
        entity_id: climate.toon_thermostat
        data:
          preset_mode: "home"

  # - alias: "Warn fish did not get food"
  #   trigger:
  #     platform: time
  #     at: "19:45:00"
  #   condition:
  #     - condition: state
  #       entity_id: input_boolean.fish_got_food
  #       state: "off"
  #   action:
  #     - service: notify.phones_kees_marleen
  #       data:
  #         message: "Hebben de vissen wel eten gehad?" 

  - id: trapkast_door_open
    alias: Trapkast Door Open
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000ad82338_contact
        to: "on"
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.shellyplus1_80646fdaacf0_switch_0

  - id: trapkast_door_closed
    alias: Trapkast Door Closed
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000ad82338_contact
        to: "off"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.shellyplus1_80646fdaacf0_switch_0


script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
      - service: sonos.snapshot
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: sonos.unjoin
        data_template:
          entity_id: "{{ sonos_entity }}"
      - service: media_player.volume_set
        data_template:
          entity_id: "{{ sonos_entity }}"
          volume_level: "{{ volume }}"
      - service: tts.google_translate_say
        data_template:
          entity_id: "{{ sonos_entity }}"
          message: "{{ message }}"
      - delay: "00:00:08"
      - service: sonos.restore
        data_template:
          entity_id: "{{ sonos_entity }}"

climate:
  - platform: toon_climate
    host: eneco-001-039306.localdomain

sensor:
  - platform: toon_smartmeter
    host: eneco-001-039306.localdomain
    resources:
      - gasused
      - gasusedcnt
      - elecusageflowpulse
      - elecusagecntpulse
      - elecusageflowlow
      - elecusagecntlow
      - elecusageflowhigh
      - elecusagecnthigh
      - heat
