homeassistant:
  customize:
    binary_sensor.burner_status:
      friendly_name: CV
          
    sensor.gas_today:
      friendly_name: Gas
          
    sensor.power_today:
      friendly_name: Electra
          
    climate.thermostat:
      friendly_name: Toon
        
    sensor.rotterdam_condition:
      friendly_name: Outside Today

    sensor.rotterdam_temperature:
      friendly_name: Outside Today

    camera.locations:
      friendly_name: Location Kees & Marleen

  
automation:
  - id: GetSonoffStateOnHAStartUp
    alias: "Get Sonoff state on HA start-up"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/power1"
          payload: ""

  - id: HassioBootNotification
    alias: "Notification when Hassio boots"
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: shell_command.install_imagemagick
    - service: notify.mobile_app_iphone
      data:
          title: "Hassio boots"
          message: "Hassio boots"
         
  
  - alias: Montly Backup
    id: montly_backup_and_cleaning
    trigger:
      platform: time
      at: '23:00:00'
    condition:
      - condition: template
        value_template: "{{ now().day == 1 }}"
    action:
      - service: hassio.snapshot_partial
        data_template:
          name: "Automated Backup {{ now().strftime('%Y-%m-%d') }}"
          addons:
            - 7be23ff5_dropbox_sync
            - core_git_pull
            - a0d7b954_ssh
            - a0d7b954_vscode
            - 7ad98f9c_zigbee2mqtt
            - addons_local
            - core_duckdns
            - core_mariadb
            - core_mosquitto
            - core_samba
            - core_ssh
          folders:
            - homeassistant
            - share
            - ssl
            - media
      - service: notify.mobile_app_iphone
        data:
            title: "Snapshot created"
            message: "Created backup of HA"
      - service: shell_command.delete_old_snapshots
      - service: hassio.addon_stdin
        data:
          addon: "7be23ff5_dropbox_sync"
          input:
            command: "upload" 

  - alias: Daily cleanup photos
    id: daily_cleanup_photos
    trigger:
      platform: time
      at: '22:00:00' 
    action:
      - service: shell_command.clean_up